/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as subscriptionSol from "./Subscription.sol";
export type { subscriptionSol };
export type { Patreon } from "./Patreon";
