import Button from '$components/Button/Button'
import SearchBox from '$components/SearchBox/SearchBox'
import Footer from '$layouts/Footer/Footer'
import UserPageHeader from '$layouts/UserPageHeader/UserPageHeader'
import CreatorsSearchIcon from '$svg/creators_search_icon'
import UserFooterLogo from '$svg/user_footer_logo'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'

const Home: NextPage = () => {
  return (
    <div className='bg-white min-h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='font-Gilroy lg3:container mx-auto'>
          <UserPageHeader className='px-2 md:px-7 lg:px-16' />
          <div className='w-full max-w-612px mx-auto mt-8 md:mt-14'>
            <SearchBox leftPosition="left-7" SearchIcon={CreatorsSearchIcon} className="w-full max-w-477px pl-20 pr-4 bg-gray4 rounded-5xl text-base md:text-lg font-normal text-gray5 text-opacity-60" height="h-12 md:h-16" placeholder="Type creators wallet id" rightSpacing="mr-8">
              <Button px="px-6 md:px-10" height="h-12 md:h-55px" onClick={()=> {}} text="Search" type="primary" className='ml-8'  />
            </SearchBox>

          </div>
      </main>
      <Footer theme={{fill: "#333333", text1: "text-black", text2: "text-black", LogoSVG: UserFooterLogo}} />
    </div>
  )
}

export default Home
