import Footer from '$layouts/Footer/Footer'
import UserPageHeader from '$layouts/UserPageHeader/UserPageHeader'
import UserFooterLogo from '$svg/user_footer_logo'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'

const Home: NextPage = () => {
  const [isOpen, setIsOpen] = useState<boolean>(false)
  return (
    <div className='bg-white min-h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='font-Gilroy lg3:container mx-auto'>
          <UserPageHeader className='px-2 md:px-7 lg:px-16' />
          <div className="flex items-center px-6 md:px-12 lg:px-24"></div>
      </main>
      <Footer theme={{fill: "#333333", text1: "text-black", text2: "text-black", LogoSVG: UserFooterLogo}} />
    </div>
  )
}

export default Home
