import Button from '$components/Button/Button'
import LandingPageHeader from '$layouts/LandingPageHeader/LandingPageHeader'
import LandingPageHero from '$layouts/LandingPageHero/LandingPageHero'
import LandingPageHowTo from '$layouts/LandingPageHowTo/LandingPageHowTo'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className='bg-dark min-h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='font-Gilroy lg3:container mx-auto px-6 md:px-12 lg:px-24'>
        <LandingPageHeader />
        <LandingPageHero />
        <LandingPageHowTo />
      </main>
    </div>
  )
}

export default Home
